package civ6save

import "hash/crc32"

func civCRC(s string) uint32 {
	return ^crc32.ChecksumIEEE([]byte(s))
}

var knownBuildingIDs = []string{
	"BUILDING_PALACE",
	"BUILDING_MONUMENT",
	"BUILDING_GRANARY",
	"BUILDING_WATER_MILL",
	"BUILDING_SEWER",
	"BUILDING_FLOOD_BARRIER",

	"BUILDING_BARRACKS",
	"BUILDING_STABLE",
	"BUILDING_ARMORY",
	"BUILDING_MILITARY_ACADEMY",
	"BUILDING_ORDU",
	"BUILDING_BASILIKOI_PAIDES",

	"BUILDING_SHRINE",
	"BUILDING_TEMPLE",
	"BUILDING_STAVE_CHURCH",
	"BUILDING_PRASAT",
	"BUILDING_WAT",
	"BUILDING_DAR_E_MEHR",
	"BUILDING_CATHEDRAL",
	"BUILDING_PAGODA",
	"BUILDING_MOSQUE",
	"BUILDING_GURDWARA",
	"BUILDING_SYNAGOGUE",
	"BUILDING_STUPA",
	"BUILDING_MEETING_HOUSE",

	"BUILDING_LIBRARY",
	"BUILDING_UNIVERSITY",
	"BUILDING_RESEARCH_LAB",
	"BUILDING_MADRASA",
	"BUILDING_NAVIGATION_SCHOOL",

	"BUILDING_AMPHITHEATER",
	"BUILDING_MUSEUM_ART",
	"BUILDING_MUSEUM_ARTIFACT",
	"BUILDING_BROADCAST_CENTER",
	"BUILDING_FILM_STUDIO",

	"BUILDING_MARKET",
	"BUILDING_BANK",
	"BUILDING_STOCK_EXCHANGE",
	"BUILDING_GRAND_BAZAAR",
	"BUILDING_SUKIENNICE",

	"BUILDING_LIGHTHOUSE",
	"BUILDING_SHIPYARD",
	"BUILDING_SEAPORT",
	"BUILDING_COTHON",

	"BUILDING_WORKSHOP",
	"BUILDING_FACTORY",
	"BUILDING_POWER_PLANT",
	"BUILDING_COAL_POWER_PLANT",
	"BUILDING_OIL_POWER_PLANT",
	"BUILDING_FOSSIL_FUEL_POWER_PLANT",
	"BUILDING_ELECTRONICS_FACTORY",

	"BUILDING_ARENA",
	"BUILDING_ZOO",
	"BUILDING_STADIUM",
	"BUILDING_TLACHTLI",
	"BUILDING_FERRIS_WHEEL",
	"BUILDING_AQUARIUM",
	"BUILDING_AQUATICS_CENTER",
	"BUILDING_THERMAL_BATH",

	"BUILDING_AIRPORT",
	"BUILDING_HANGAR",

	"BUILDING_FOOD_MARKET",
	"BUILDING_SHOPPING_MALL",

	"BUILDING_CONSULATE",
	"BUILDING_CHANCERY",

	"BUILDING_GROVE",
	"BUILDING_SANCTUARY",

	"BUILDING_ANCIENT_WALLS",
	"BUILDING_MEDIEVAL_WALLS",
	"BUILDING_RENAISSANCE_WALLS",
	"BUILDING_STAR_FORT",
	"BUILDING_TSIKHE",

	// Government plaza buildings
	"BUILDING_AUDIENCE_CHAMBER",
	"BUILDING_ANCESTRAL_HALL",
	"BUILDING_WARLORD_THRONE",
	"BUILDING_WARLORDS_THRONE",
	"BUILDING_FOREIGN_MINISTRY",
	"BUILDING_GRAND_MASTERS_CHAPEL",
	"BUILDING_INTELLIGENCE_AGENCY",
	"BUILDING_ROYAL_SOCIETY",
	"BUILDING_WAR_DEPARTMENT",
	"BUILDING_NATIONAL_HISTORY_MUSEUM",

	// Secret societies / mode replacements
	"BUILDING_OLD_GOD_OBELISK",
	"BUILDING_GILDED_VAULT",
	"BUILDING_ALCHEMICAL_SOCIETY",

	// Save aliases seen in BBG/modded saves
	"BUILDING_WALLS",
	"BUILDING_CASTLE",
	"BUILDING_GOV_WIDE",
	"BUILDING_GOV_TALL",
	"BUILDING_GOV_CONQUEST",
	"BUILDING_GOV_CULTURE",
	"BUILDING_GOV_SCIENCE",
	"BUILDING_GOV_FAITH",
	"BUILDING_GOV_CITYSTATES",
	"BUILDING_GOV_MILITARY",
	"BUILDING_GOV_SPIES",
}

var knownBuildingNames = func() map[uint32]string {
	m := make(map[uint32]string, len(knownBuildingIDs))
	for _, n := range knownBuildingIDs {
		m[civCRC(n)] = n
	}
	return m
}()

var knownBuildingCRCs = func() map[uint32]bool {
	m := make(map[uint32]bool, len(knownBuildingNames))
	for crc := range knownBuildingNames {
		m[crc] = true
	}
	return m
}()

func IsKnownBuildingCRC(crc uint32) bool {
	return knownBuildingCRCs[crc]
}

func BuildingNameByCRC(crc uint32) (string, bool) {
	n, ok := knownBuildingNames[crc]
	return n, ok
}
